### ISSUE TITLE
Missing ansi.h and banner.h

### ISSUE THREAD

**Issue by sgvandijk** [Fastcode/NUClearRoles#1]
`generate_roles.py` generates:

    #include "utility/strutil/ansi.h"
    #include "utility/strutil/banner.h"

However these don't exist here; they are in the NUbots code base.

**Comment by TrentHouliston** [comment]
I have been meaning to implement something that would obsolete these, so I guess now is a good time to go build it.

**Comment by TrentHouliston** [comment]
Fixed, those headers are no longer used.
Instead the banner is generated from an Image file directly

**Comment by sgvandijk** [comment]
Nice, that's cool! Just one small issue: need to update banner.txt to banner.png in NUClearRoles/CMakeLists.txt

**Comment by TrentHouliston** [comment]
Nice catch, fixed.
I also started to document some of the NUClear roles things in README.md.
I'll add some more when I get some time
