### ISSUE TITLE
Option to choose or deduce file extensions

### ISSUE THREAD

**Issue by sgvandijk** [Fastcode/NUClearRoles#3]
Currently you are forced to use `.h` for module headers: NUClearModule globs for .hpp, .ipp, and .h (would be nice to have .hh included), but `generate_role.py` only works with .h.

**Comment by TrentHouliston** [comment]
Fixed: NUClearModule now globs for .hh as well, and generate_role tries to deduce the extension (it will try hpp then hh then h)
